In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy


In [2]:
l1 = 1
l2 = 1
m1 = 1
m2 = 1
Iz1 = m1 * (l1/2)**2
Iz2 = m2 * (l2/2)**2

In [3]:
state = np.array([np.pi/2, np.pi/2, 0, 0])  # [theta1, theta2, theta1_dot, theta2_dot]

In [6]:
tau1 = 0
tau2 = 0
theta1, theta2, theta1_dot, theta2_dot = state
delta = Iz2 + m2 * l2**2
beta =  m2 * l1 * l2
alpha = Iz1 + Iz2 + m1 * l1**2 + beta

In [7]:
theta1

1.5707963267948966

In [8]:
C = np.array([[-beta * np.sin(theta2) * theta2_dot, beta * np.sin(theta2) * (theta1_dot + theta2_dot)],
                [beta * np.sin(theta2) * theta1_dot, 0]])
C

array([[-0.,  0.],
       [ 0.,  0.]])

In [9]:
M = np.array([[alpha + 2 * beta * np.cos(theta2), delta + beta * np.cos(theta2)],
                [delta + beta * np.cos(theta2), delta]])
M

array([[2.5 , 1.25],
       [1.25, 1.25]])

In [10]:
velocities = np.array([theta1_dot,theta2_dot])
velocities

array([0., 0.])

In [11]:
Tau = np.array([tau1,tau2])
Tau

array([0, 0])

In [13]:
intermediate1 = C @ velocities
intermediate1

array([0., 0.])

In [14]:
intermediate2 = Tau - intermediate1
intermediate2

array([0., 0.])

In [15]:
intermediate3 = np.linalg.inv(M)

In [16]:
intermediate3

array([[ 0.8, -0.8],
       [-0.8,  1.6]])

In [17]:
accelerations = intermediate3@intermediate2

In [18]:
accelerations

array([0., 0.])

In [19]:
result = np.linalg.inv(M)@(Tau-(C@velocities))
result

array([0., 0.])